DELETE http://localhost:3001/api/persons/693c5dec31d319e72d5cdfe6


###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "John Doe",
    "number": "555-1234"
}

###
GET http://localhost:3001/api/persons/69442bd60de86ec334d3f6f8

